sudo: required
dist: trusty
services:
- docker
script:
- docker run -v $(pwd):/cwd snapcore/snapcraft sh -c 'cd /cwd && snapcraft'
after_success:
- openssl aes-256-cbc -K $encrypted_fd5960f2dcc4_key -iv $encrypted_fd5960f2dcc4_iv
  -in .travis_snapcraft.cfg -out .snapcraft.cfg -d
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t ubuntu:xenial sh -c "apt update -qq && apt
    install snapcraft -y && cd $(pwd) && snapcraft && snapcraft push *.snap --release
    edge"
  skip_cleanup: true
